// <auto-generated />
using System;
using System.Collections.Generic;
using InterviewBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.DayLog", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.HasKey("Date")
                        .HasName("pk_day_logs");

                    b.ToTable("day_logs", (string)null);
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.Digest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Feedback")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("feedback");

                    b.Property<DateOnly>("ForDate")
                        .HasColumnType("date")
                        .HasColumnName("for_date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("SnippetHtml")
                        .HasColumnType("text")
                        .HasColumnName("snippet_html");

                    b.Property<string>("SnippetPermalink")
                        .HasColumnType("text")
                        .HasColumnName("snippet_permalink");

                    b.Property<DateTimeOffset?>("SnippetSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snippet_sent_at");

                    b.Property<DateTimeOffset?>("TasksSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tasks_sent_at");

                    b.Property<string>("TheoryHtml")
                        .HasColumnType("text")
                        .HasColumnName("theory_html");

                    b.Property<DateTimeOffset?>("TheorySentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("theory_sent_at");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_digests");

                    b.HasIndex("ForDate")
                        .IsUnique()
                        .HasDatabaseName("ix_digests_for_date")
                        .HasFilter("kind = 'Daily'");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_digests_topic_id");

                    b.ToTable("digests", (string)null);
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.PracticeTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Complexity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complexity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DigestId")
                        .HasColumnType("uuid")
                        .HasColumnName("digest_id");

                    b.PrimitiveCollection<List<string>>("ExpectedQuestions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("expected_questions");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<int>("OrderInDigest")
                        .HasColumnType("integer")
                        .HasColumnName("order_in_digest");

                    b.Property<string>("ReferenceSolution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_solution");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SolutionExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solution_explanation");

                    b.Property<DateTimeOffset?>("SolutionRevealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("solution_revealed_at");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_practice_tasks");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_practice_tasks_created_at");

                    b.HasIndex("DigestId")
                        .HasDatabaseName("ix_practice_tasks_digest_id");

                    b.HasIndex("TelegramMessageId")
                        .HasDatabaseName("ix_practice_tasks_telegram_message_id");

                    b.ToTable("practice_tasks", (string)null);
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.TaskAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<bool>("AskedClarifyingQuestions")
                        .HasColumnType("boolean")
                        .HasColumnName("asked_clarifying_questions");

                    b.Property<string>("ReviewHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_html");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_attempts");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_attempts_task_id");

                    b.ToTable("task_attempts", (string)null);
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Module")
                        .HasColumnType("integer")
                        .HasColumnName("module");

                    b.Property<string>("ModuleTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module_title");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.TopicProgress", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic_id");

                    b.Property<DateOnly?>("LastShownOn")
                        .HasColumnType("date")
                        .HasColumnName("last_shown_on");

                    b.Property<DateOnly?>("NextReviewOn")
                        .HasColumnType("date")
                        .HasColumnName("next_review_on");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("StatusChangedOn")
                        .HasColumnType("date")
                        .HasColumnName("status_changed_on");

                    b.HasKey("TopicId")
                        .HasName("pk_topic_progress");

                    b.ToTable("topic_progress", (string)null);
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.UserSettings", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("PausedUntil")
                        .HasColumnType("date")
                        .HasColumnName("paused_until");

                    b.Property<TimeOnly>("SendTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("send_time");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("WeekendMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("weekend_mode");

                    b.HasKey("TelegramUserId")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.Digest", b =>
                {
                    b.HasOne("InterviewBot.Infrastructure.Persistence.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_digests_topics_topic_id");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.PracticeTask", b =>
                {
                    b.HasOne("InterviewBot.Infrastructure.Persistence.Digest", null)
                        .WithMany("Tasks")
                        .HasForeignKey("DigestId")
                        .HasConstraintName("fk_practice_tasks_digests_digest_id");
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.TaskAttempt", b =>
                {
                    b.HasOne("InterviewBot.Infrastructure.Persistence.PracticeTask", "Task")
                        .WithMany("Attempts")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_attempts_practice_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.Topic", b =>
                {
                    b.OwnsMany("InterviewBot.Infrastructure.Persistence.CodeRef", "CodeRefs", b1 =>
                        {
                            b1.Property<string>("TopicId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Path")
                                .IsRequired();

                            b1.Property<string>("Repo")
                                .IsRequired();

                            b1.Property<string>("Symbol")
                                .IsRequired();

                            b1.HasKey("TopicId", "__synthesizedOrdinal");

                            b1.ToTable("topics");

                            b1
                                .ToJson("code_refs")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TopicId")
                                .HasConstraintName("fk_topics_topics_topic_id");
                        });

                    b.Navigation("CodeRefs");
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.TopicProgress", b =>
                {
                    b.HasOne("InterviewBot.Infrastructure.Persistence.Topic", null)
                        .WithOne("Progress")
                        .HasForeignKey("InterviewBot.Infrastructure.Persistence.TopicProgress", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topic_progress_topics_topic_id");
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.Digest", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.PracticeTask", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("InterviewBot.Infrastructure.Persistence.Topic", b =>
                {
                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
